spring:
  application:
    name: risk-finder

  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3306/risk_finder?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.password}

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: ${jwt.secret}
  AccessExpiration: 86400000  # 24시간
  refreshExpiration: 604800000  # 7일

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

path:
  loan-main: ${path.loan-main}
  customer-contact: ${path.customer-contact}
  customer-info: ${path.customer-info}
  customer-docs: ${path.customer-docs}
  customer-residence: ${path.customer-residence}